# Generated by Django 2.2.4 on 2023-12-29 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
