# Generated by Django 2.2.4 on 2023-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guest_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='package',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
