# Generated by Django 2.2.4 on 2023-12-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231231_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='number_of_person',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='number_of_person',
            field=models.IntegerField(default=2),
        ),
    ]
