# Generated by Django 2.2.4 on 2024-01-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240101_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cvc',
            field=models.IntegerField(default='123'),
        ),
        migrations.AddField(
            model_name='bill',
            name='email_palpay',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='firstname_visa',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='lastname_visa',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='pass_palpay',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
