# Generated by Django 2.2.4 on 2024-01-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240102_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='method',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone_number',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='bill',
            name='region',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
