# Generated by Django 2.2.4 on 2024-01-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240103_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='expiration',
        ),
    ]
