# Generated by Django 2.2.4 on 2024-01-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240105_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_amount',
        ),
        migrations.AddField(
            model_name='package',
            name='likes_package',
            field=models.ManyToManyField(related_name='guest_likes', to='app.Guest'),
        ),
    ]
