# Generated by Django 2.2.4 on 2024-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240106_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='email_palpay',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pass_palpay',
        ),
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.IntegerField(default='123'),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(default='123'),
        ),
    ]
